publicRepository:
  authorName: "DVSA"
  authorEmail: "dvsa@dvsa.gov.uk"
  authorFullName: "DVSA <dvsa@dvsa.gov.uk>"
  initialCommitDate: "Wed Jun 17 14:00 2015 +0100"
  publishingHistoryFileName: "patch-history.json"
  publishingDiffFileName: "src/main/resources/diff.json"
  publicRepoUrl: "https://github.com/KainosSoftwareLtd/dvsa-mot.git"
  initialCommitMessage: "Application v1.9.5.4"
  destinationBranchName: "public-master"
  destinationRemoteBranchName: "master"
  skippedCommitMessage: "##SKIP"

privateRepository:
  commitHistoryFileName: "mot-commit-history.json"
  firstCommitInRepository: "9a86b3d7741d84c6774b75319ccf6581d7adf5cd"
  lastSquashedCommit: "61f3b67a5163087cdedb037074cc80a59842d151"
  sourceBranchName: "master"
  skippedCommits:
    - "be672b6eb00f35c58e6fa020b24945a77af91687"
    - "f62199d3dc535d0aba83ddc70df71b3852fa29c9"
    - "da41bb875c32f5a297845b0d2a5fbb9a70f722c6"

jira:
  ticketNumberFormat: "((BL|MDM|VM)-[0-9]{1,6})"
  jiraApiUrl: "https://jira.i-env.net/rest/api/latest/issue/"

